version: '3.9'
services:

  etcd1:
    image: bitnami/etcd:3.5.0
    restart: on-failure
    environment:
      ALLOW_NONE_AUTHENTICATION: "no"
      ETCD_ROOT_PASSWORD: kqN9jRKb3sF6g9BTwzVA6Z7NW35Hd3MN
      ETCD_NAME: etcd1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd1:2379
      ETCD_INITIAL_CLUSTER_TOKEN: g59hQk2J9ZyhMg4y
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
    volumes:
      - etcd1-data:/bitnami/etcd

  etcd2:
    image: bitnami/etcd:3.5.0
    restart: on-failure
    environment:
      ALLOW_NONE_AUTHENTICATION: "no"
      ETCD_ROOT_PASSWORD: kqN9jRKb3sF6g9BTwzVA6Z7NW35Hd3MN
      ETCD_NAME: etcd2
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd2:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd2:2379
      ETCD_INITIAL_CLUSTER_TOKEN: g59hQk2J9ZyhMg4y
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
    volumes:
      - etcd2-data:/bitnami/etcd

  etcd3:
    image: bitnami/etcd:3.5.0
    restart: on-failure
    environment:
      ALLOW_NONE_AUTHENTICATION: "no"
      ETCD_ROOT_PASSWORD: kqN9jRKb3sF6g9BTwzVA6Z7NW35Hd3MN
      ETCD_NAME: etcd3
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd3:2380
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd3:2379
      ETCD_INITIAL_CLUSTER_TOKEN: g59hQk2J9ZyhMg4y
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
    volumes:
      - etcd3-data:/bitnami/etcd

volumes:
  etcd1-data:
    driver: local
    labels:
      service: etcd
  etcd2-data:
    driver: local
    labels:
      service: etcd
  etcd3-data:
    driver: local
    labels:
      service: etcd
